### ISSUE TITLE
PrivacyPolicy

### ISSUE THREAD

**Issue by SerjantArbuz** [ilimurzin/ArhLib#1]
Добавь **privacy policy** в приложение и на страничку в маркете, потому что могут забанить в google play: [link](https://support.google.com/googleplay/android-developer/answer/9859455?hl=en#:~:text=Add%20a%20privacy%20policy,select%20Manage%20instead%20of%20start.)

**Comment by ilimurzin** [comment]
Заказчик отказался от поддержки приложения, так что закрываю

Спасибо за заботу ❤️
